services:
  mongo:
    image: mongo:4.4
    container_name: mongo_transporte
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: transporte
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    image: actividad2:1.0
    container_name: api_transporte
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://root:rootpass@mongo:27017/transporte?authSource=admin
      SPRING_MAIN_WEB_APPLICATION_TYPE: servlet
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  mongo_data:
