spring:
  application:
    name: JesusMartinezAlonso-Actividad2
  data:
    mongodb:
      uri: mongodb://localhost:27017/transporte
      auto-index-creation: true
  profiles:
    active: default

server:
  port: 8080

jwt:
  secret: "c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0"
  expiration-ms: 86400000
